---
# Debug/sanity
- debug:
    msg:
      - "Site Code: {{ ansible_local.site.sitecode }}"

# Site specific
- include_vars: site_{{ ansible_local.site.sitecode }}.yml

# Task that sets the timezone and configures chrony
- import_tasks: time.yml
