---
# Debug/sanity
- debug:
    msg:
      - "Site Code: {{ ansible_local.site.sitecode }}"

# Site specific
- include_vars: vars/sites/site_{{ ansible_local.site.sitecode }}.yml

# Task that sets the timezone and configures chrony
- import_tasks: subtasks/time.yml
- import_tasks: subtasks/sshd.yml
