---
# Debug/sanity
- debug:
    msg:
      - "Site Code: {{ site-code }}"

# Site specific
- include_vars: vars/sites/site_{{ sitecode }}.yml

# Task that sets the timezone and configures chrony
- import_tasks: subtasks/time.yml
# Configures SSHD
- import_tasks: subtasks/sshd.yml
# Adds default user groups
- import_tasks: subtasks/groups.yml
# Update System admin accounts
- import_tasks: subtasks/system_admins.yml
# Default packages
- import_tasks: subtasks/packages.yml
# Base files
- import_tasks: subtasks/files.yml
